# Generated by Django 5.0 on 2024-01-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CAProfile',
            fields=[
                ('fullname', models.TextField()),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=15)),
                ('college', models.TextField()),
                ('year', models.IntegerField()),
                ('CA', models.CharField(max_length=6, unique=True)),
            ],
        ),
    ]
