# Generated by Django 5.0 on 2024-01-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_institute_rename_year_profile_joinyear_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='userId',
        ),
        migrations.AlterField(
            model_name='institute',
            name='institutionType',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
